coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    # disabled until total coverage increased to approx 75%
    # patch:
    #   default:
    #     target: 80%
